config/routes.rb
Rails.application.routes.draw do

  root 'matters#index'
  get 'matters/index'
  
  get 'matters/find' => 'matters#find'
  

    resources :matters

end

app/models/matter.rb
class Matter < ActiveRecord::Base
    def self.search(search)
        where("name_or_type LIKE ? OR description LIKE ? OR notes LIKE ? OR title LIKE ? OR artist_or_band LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
    end
    
    def self.find_it_by(finders)
       
        @finders = finders
        puts "Puts"
        puts "#{@finders}"
        @checkit = where(@finders).to_sql
        puts "#{@checkit}"
       # where(@finders)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  before_action :set_matter, only: [:show, :edit, :update, :destroy]
  
  

  # GET /matters
  # GET /matters.json
  def index
    @matters = Matter.all
    if params[:search]
      @matters = Matter.search(params[:search]).order("created_at DESC")
    else
      @matters = Matter.all.order("created_at DESC")
    end
  end

  def find
    @terms = nil
    @matters = Matter.all
    puts "Controller 0"
    puts "#{params}"
    if params[:commit]
      @special_hash = {"acquired_date_T" => ":acquired_date" , "loaned_date_T" => ":loaned_date", "released_date_T" => ":released_date"}
      @not_special_array = ["utf8", "commit", "controller", "action"]
      params.each do |k,v|
        puts "Out Here #{k}, #{v} #{@terms}"
        next if @not_special_array.include? k.to_s
        puts "Here Maybe #{k}, #{v} #{@terms}"
        next if v.blank? unless @special_hash.include? k.to_s
        clean = v.gsub(/[^A-Za-z0-9 ]/, '')
        puts "Right Cheer #{k}, #{v}, #{clean},  #{@terms}"
        if clean.blank?
          clean = @special_hash.fetch(k.to_s)
          puts "In Here #{k}, #{v}, #{clean}, #{@terms}"
          @terms = "#{@terms} AND #{clean} != NULL" unless @terms.blank? 
            @terms ||= "#{clean} != NULL"
        else
          @terms = "#{@terms} AND #{k} LIKE '%#{clean.strip}%'" unless @terms.blank? 
            @terms ||= "#{k} LIKE '%#{clean.strip}%'"
            puts "In There #{k}, #{v}, #{clean}, #{@terms}"
        end          
      end
      puts "Controller" 
      puts "Terms #{@terms}"
      
      #@matters = Matter.find_it_by(@terms).order("created_at DESC")
      @matters = Matter.find_it_by(@terms)
      #@matters.blank?
      render :index, collection: @matters #unless @matters.blank?
    else
      render :find
    end
  end

  # GET /matters/1
  # GET /matters/1.json
  def show
  end

  # GET /matters/new
  def new
    @matter = Matter.new
  end

  # GET /matters/1/edit
  def edit
  end

  # POST /matters
  # POST /matters.json
  def create
    @matter = Matter.new(matter_params)

    respond_to do |format|
      if @matter.save
        format.html { redirect_to @matter, notice: 'Matter was successfully created.' }
        format.json { render :show, status: :created, location: @matter }
      else
        format.html { render :new }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matters/1
  # PATCH/PUT /matters/1.json
  def update
    respond_to do |format|
      if @matter.update(matter_params)
        format.html { redirect_to @matter, notice: 'Matter was successfully updated.' }
        format.json { render :show, status: :ok, location: @matter }
      else
        format.html { render :edit }
        format.json { render json: @matter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matters/1
  # DELETE /matters/1.json
  def destroy
    @matter.destroy
    respond_to do |format|
      format.html { redirect_to matters_url, notice: 'Matter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matter
      @matter = Matter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matter_params
      params.require(:matter).permit(:name_or_type, :location, :acquired_date, :value, :loaned_to, :loaned_date, :description, :notes, :upc_barcode, :title, :released_date, :format, :artist_or_band, :track_list, :amateur, :lineage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matters_helper.rb
module MattersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%#=# yield %>
<h1 class="title">
  <%= link_to "Media Matters Catalog", controller: 'matters' %>
</h1>

<%= form_tag(matters_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Matters" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<div id="content">
  <%= content_for?(:content) ? yield(:content) : yield %>
</div>
<div id="main">
  <% if flash[:notice] %>
    <div class="message" id="notice">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:warning] %>
    <div class="message" id="warning">
      <%= flash[:warning] %>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/matters/_find_form.html.erb
<%= form_tag(matters_find_path, :method => "get", id: "find-form") do  %>
 
  <div class="field">
     <label style="width:300px;"> Name or Type (media, movie, music, or book): </label>
    <%= text_field_tag :name_or_type, nil, placeholder: 'Alpha-Numeric Only', size: 50 %>
  </div>
  <div class="field">
   <label style="width:300px;"> Location: <%= text_field_tag 'location', nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
   <label style="width:300px;"> Date Acquired: </label>
    <label><%= date_field_tag :acquired_date, ' ', size: 50 %> <%= check_box_tag :acquired_date_T, ' ', checked = false %>   Date Not Blank ?   </label>
  </div>
  <div class="field">
    <label style="width:300px;"> Value: <%= number_field_tag :value,  nil, placeholder: 'Alpha-Numeric Only', size: 50 %> </label>
  </div>
  <div class="field">
    <label style="width:300px;"> Loaned To: <%= text_field_tag :loaned_to,  nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Date Loaned: </label>
    <label><%= date_field_tag :loaned_date, ' ', size:50 %> <%= check_box_tag :loaned_date_T, ' ', checked = false %>   Date Not Blank ?   </label>
  </div>
  <div class="field">
    <label style="width:300px;"> Item Description: <%= text_field_tag :description, nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Notes: <%= text_field_tag :notes, nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> UPC Barcode: <%= number_field_tag :upc_barcode, ' ', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Title: <%= text_field_tag :title,  nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Released Date: </label>
    <label><%= date_field_tag :released_date, ' ', size: 50 %><%= check_box_tag :released_date_T, ' ', checked = false %>   Date Not Blank ?   </label>
  </div>
  <div class="field">
    <label style="width:300px;"> Media Format: <%= text_field_tag :format, nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Artist or Band <%= text_field_tag :artist_or_band, nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Contents or Track List: <%= text_field_tag :track_list, nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="field">
    <label style="width:300px;"> Amateur: </label>
    <%= check_box_tag :amateur, ' ', checked = false, size: 50 %>
  </div>
  <div class="field">
    <label style="width:300px;"> Lineage: <%= text_field_tag :lineage, nil, placeholder: 'Alpha-Numeric Only', size: 50 %></label>
  </div>
  <div class="actions">
    <%= submit_tag "Find Matter", data: { disable_with: "Searching..." } %>
  </div>
 
 <% end %>

app/views/matters/_form.html.erb
<%= form_for(@matter) do |f| %>
  <% if @matter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matter.errors.count, "error") %> prohibited this matter from being saved:</h2>

      <ul>
      <% @matter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name_or_type %><br>
    <!--
      <%= f.select :name_or_type, options_for_select([ "media", "music", "movie", "book"]) %>
    -->
    <%= f.text_field :name_or_type %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :acquired_date %><br>
    <%= f.date_select :acquired_date, start_year: Date.today.year - 80, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :loaned_to %><br>
    <%= f.text_field :loaned_to %>
  </div>
  <div class="field">
    <%= f.label :loaned_date %><br>
    <%= f.date_select :loaned_date, start_year: Date.today.year - 80, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :upc_barcode %><br>
    <%= f.number_field :upc_barcode %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :released_date %><br>
    <%= f.date_select :released_date, start_year: Date.today.year - 150, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :artist_or_band %><br>
    <%= f.text_field :artist_or_band %>
  </div>
  <div class="field">
    <%= f.label :track_list %><br>
    <%= f.text_area :track_list %>
  </div>
  <div class="field">
    <%= f.label :amateur %><br>
    <%= f.check_box :amateur %>
  </div>
  <div class="field">
    <%= f.label :lineage %><br>
    <%= f.text_area :lineage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matters/edit.html.erb
<h1>Editing Matter</h1>

<%= render 'form' %>

<%= link_to 'Show', @matter %> |
<%= link_to 'Back', matters_path %>

app/views/matters/find.html.erb
<h1>Find Matter</h1>

<%= render 'find_form' %>

<%= link_to 'Back', matters_path %>

app/views/matters/index.html.erb
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif|Lato" rel="stylesheet">/</link>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  </head>
  <body>
    <div id="BannerDiv">
      <p><h2>Media Matters Catalog</h2></p>
    </div>
  </body>
</html>

<% if @matters.blank? %>
  <h4>There are no items containing the term <%= params[:search] %>.</h4>
<% end %>

<p id="notice"><%= notice %></p>

<%= puts "Putting matters: #{@matters}" %>

<h1>Listing Matters</h1>

<table>
  <thead>
    <tr>
      <th>NameOrType</th>
      <th>Location</th>
      <th>AcquiredDate</th>
      <th>Value</th>
      <th>LoanedTo</th>
      <th>LoanedDate</th>
      <th>Description</th>
      <th>Notes</th>
      <th>UPCBarcode</th>
      <th>Title</th>
      <th>ReleasedDate</th>
      <th>Format</th>
      <th>ArtistOrBand</th>
      <th>TrackList</th>
      <th>Amateur</th>
      <th>Lineage</th>
      <th colspan="4"></th>
    </tr>
  </thead>


  <tbody>
    <% unless @matters.blank? then @matters.each do |matter| %>
      <tr>
        <td><%= matter.name_or_type.truncate(50) %></td>
        <td><%= matter.location.truncate(50) %></td>
        <td><%= matter.acquired_date %></td>
        <td><%= matter.value %></td>
        <td><%= matter.loaned_to.truncate(50) %></td>
        <td><%= matter.loaned_date %></td>
        <td><%= matter.description.truncate(50) %></td>
        <td><%= matter.notes.truncate(50) %></td>
        <td><%= matter.upc_barcode %></td>
        <td><%= matter.title.truncate(50) %></td>
        <td><%= matter.released_date %></td>
        <td><%= matter.format.truncate(50) %></td>
        <td><%= matter.artist_or_band.truncate(50) %></td>
        <td><%= matter.track_list.truncate(50) %></td>
        <td><%= matter.amateur %></td>
        <td><%= matter.lineage.truncate(50) %></td>
        <td><%= link_to 'Find', matters_find_path %></td>
        <td><%= link_to 'Show', matter %></td>
        <td><%= link_to 'Edit', edit_matter_path(matter) %></td>
        <td><%= link_to 'Destroy', matter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Matter?', new_matter_path %> 

app/views/matters/new.html.erb
<h1>New Matter</h1>

<%= render 'form' %>

<%= link_to 'Back', matters_path %>

app/views/matters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name or type:</strong>
  <%= @matter.name_or_type.truncate(200) %>
</p>

<p>
  <strong>Location:</strong>
  <%= @matter.location.truncate(200) %>
</p>

<p>
  <strong>Acquired date:</strong>
  <%= @matter.acquired_date %>
</p>

<p>
  <strong>Value:</strong>
  <%= @matter.value %>
</p>

<p>
  <strong>Loaned to:</strong>
  <%= @matter.loaned_to.truncate(200) %>
</p>

<p>
  <strong>Loaned date:</strong>
  <%= @matter.loaned_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @matter.description.truncate(200) %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @matter.notes.truncate(200) %>
</p>

<p>
  <strong>Upc barcode:</strong>
  <%= @matter.upc_barcode %>
</p>

<p>
  <strong>Title:</strong>
  <%= @matter.title.truncate(200) %>
</p>

<p>
  <strong>Released date:</strong>
  <%= @matter.released_date %>
</p>

<p>
  <strong>Format:</strong>
  <%= @matter.format.truncate(200) %>
</p>

<p>
  <strong>Artist or band:</strong>
  <%= @matter.artist_or_band.truncate(200) %>
</p>

<p>
  <strong>Track list:</strong>
  <%= @matter.track_list.truncate(200) %>
</p>

<p>
  <strong>Amateur:</strong>
  <%= @matter.amateur %>
</p>

<p>
  <strong>Lineage:</strong>
  <%= @matter.lineage.truncate(200) %>
</p>

<%= link_to 'Edit', edit_matter_path(@matter) %> |
<%= link_to 'Back', matters_path %>